---
title: "Exploratory Analysis of Titanic"
author: "Timotius Andrean Patrick Lagaunne"
output: html_document
---

#Library
```{r}
library(ggplot2)
library(dplyr)
library(zoo)
library(car)
library(lubridate)
library(lattice)
library(mice)
library(VIM)
library(gmodels)
library(randomForest)
```


#Overview of Data
```{r}
setwd("/home/lagaunne/Patrick/Back Up/Document/R/Kaggle/Titanic")
titanic<-read.csv("train.csv")
summary(titanic)
head(titanic)
tail(titanic)
str(titanic)
```

#Data manipulation
```{r}
###removing id and name since it is not useful for model
feature_extraction_titanic<-function(titanic){
titanic=titanic[,-1]
titanic=titanic[,-3]
titanic=titanic[,-9]
titanic=titanic[,-7]

titanic$Age[is.na(titanic$Age)]=mean(titanic$Age,na.rm=TRUE)

titanic$Age[titanic$Age<18]=1
titanic$Age[titanic$Age>17 & titanic$Age<30]=2
titanic$Age[titanic$Age>29 & titanic$Age<40]=3
titanic$Age[titanic$Age>39 & titanic$Age<50]=4
titanic$Age[titanic$Age>49]=5

titanic$Fare[is.na(titanic$Fare)]=1
titanic$Fare[titanic$Fare<51]=1
titanic$Fare[titanic$Fare>50 & titanic$Fare<101]=2
titanic$Fare[titanic$Fare>100]=3
titanic$Fare<-as.factor(titanic$Fare)
titanic$Age<-as.factor(titanic$Age)
titanic$SibSp<-as.factor(titanic$SibSp)
titanic$Pclass<-as.factor(titanic$Pclass)
titanic$Parch<-as.factor(titanic$Parch)
titanic$Survived<-as.factor(titanic$Survived)
return(titanic)
}
titanic<-feature_extraction_titanic(titanic)
```

#Exploratory analysis
```{r,echo=FALSE}
#Plot of Survived against Pclass
ggplot(data=titanic,aes(Pclass))+geom_bar()+facet_wrap(~Survived)
#Plot of Survived against Sex
ggplot(data=titanic,aes(Sex))+geom_bar()+facet_wrap(~Survived)
#Plot of Survived against Age
ggplot(data=titanic,aes(Age))+geom_bar()+facet_wrap(~Survived)
#Plot of Survived against SibSp
ggplot(data=titanic,aes(SibSp))+geom_bar()+facet_wrap(~Survived)
#Plot of Survived against Fare
ggplot(data=titanic,aes(Fare))+geom_bar()+facet_wrap(~Survived)
#Plot of Survived against Embarked
ggplot(data=titanic,aes(Embarked))+geom_bar()+facet_wrap(~Survived)

```

#Summary
After the exploratory analysis, it seems all the ploted are good feature for the model because the feature could differenciated whether a person going to be survived or not during the Titanic incident.
