---
title: "Titanic_Modeling"
author: "Timotius Andrean Patrick Lagaunne"
date: "January 12, 2016"
output: html_document
---

#Library
```{r}
library(ggplot2)
library(dplyr)
library(zoo)
library(car)
library(lubridate)
library(lattice)
library(mice)
library(VIM)
library(gmodels)
library(randomForest)
library(caret)
```

#Feature Engineering
```{r}
feature_extraction_titanic<-function(titanic){
titanic=titanic[,-1]
titanic=titanic[,-3]
titanic=titanic[,-9]
titanic=titanic[,-7]

titanic$Age[is.na(titanic$Age)]=mean(titanic$Age,na.rm=TRUE)
titanic$Embarked[is.na(titanic$Embarked)]="S"
titanic$Age[titanic$Age<18]=1
titanic$Age[titanic$Age>17 & titanic$Age<30]=2
titanic$Age[titanic$Age>29 & titanic$Age<40]=3
titanic$Age[titanic$Age>39 & titanic$Age<50]=4
titanic$Age[titanic$Age>49]=5

titanic$Fare[is.na(titanic$Fare)]=1
titanic$Fare[titanic$Fare<51]=1
titanic$Fare[titanic$Fare>50 & titanic$Fare<101]=2
titanic$Fare[titanic$Fare>100]=3
titanic$Fare<-as.factor(titanic$Fare)
titanic$Age<-as.factor(titanic$Age)
titanic$SibSp<-as.factor(titanic$SibSp)
titanic$Pclass<-as.factor(titanic$Pclass)
titanic$Parch<-as.factor(titanic$Parch)
titanic$Survived<-as.factor(titanic$Survived)
return(titanic)
}

```

#Model Selection
```{r,eval=FALSE}
###Data Loading
setwd("/home/lagaunne/Patrick/Back Up/Document/R/Kaggle/Titanic")
titanic_test<-read.csv("test.csv",na.strings=c("","NA"))
titanic_train<-read.csv("train.csv",na.strings=c("","NA"))
titanic_test<-cbind(titanic_test$PassengerId,"NA",titanic_test[,2:ncol(titanic_test)])
names(titanic_test)[2]<-"Survived"
names(titanic_test)[1]<-"PassengerId"
titanic<-rbind(titanic_train,titanic_test)

###Feature Construction
titanic<-feature_extraction_titanic(titanic)
titanic_train<-titanic[1:891,]
titanic_test<-titanic[892:nrow(titanic),]

###Training and Test data construction
trainindex<-createDataPartition(titanic_train$Survived,p=.8,list=FALSE,times=1)

train_titanic<-titanic_train[trainindex,-1]
class_train_titanic<-titanic_train[trainindex,1]
test_titanic<-titanic_train[-trainindex,-1]
class_test_titanic<-titanic_train[-trainindex,1]
class_train_titanic<-droplevels(class_train_titanic)
###Model Training and Checking
first_user_model<-randomForest(train_titanic,class_train_titanic,ntree=25,mtry=3)
p<-predict(first_user_model,test_titanic,type="response")
CrossTable(x=class_test_titanic,y=p,prop.chisq=FALSE)
###Model Prediction
m<-predict(first_user_model,titanic_test,type="response")
m<-as.vector(m)
sample<-read.csv("test.csv")
sample<-cbind(sample[1],m)
names(sample)[2]<-"Survived"
names(sample)[1]<-"PassengerId"
write.csv(sample,file="finalresult.csv",row.names=FALSE)



```


